export const mockChamas = [
  {
    id: 1,
    name: "Women Entrepreneurs Chama",
    description:
      "Supporting women entrepreneurs in building successful businesses and financial independence",
    members: 8,
    totalMembers: 10,
    maxMembers: 10,
    contribution: 5000,
    frequency: "Monthly",
    duration: "10 months",
    rating: 4.7,
    category: "Professional",
    location: "Nairobi",
    tags: ["Women", "Entrepreneurship", "Business"],
    collateralRequired: 5000,
    nextPayout: "2025-02-15",
    myTurn: false,
    nextTurnMember: "Grace Wanjiku",
    status: "active",
    unreadMessages: 3,
    currency: "KES",
    isPublic: false,
  },
  {
    id: 2,
    name: "Tech Developers Circle",
    description:
      "A community of software developers pooling resources for career growth and tech investments",
    members: 12,
    totalMembers: 12,
    maxMembers: 12,
    contribution: 10000,
    frequency: "Monthly",
    duration: "12 months",
    rating: 4.9,
    category: "Professional",
    location: "Global",
    tags: ["Technology", "Software", "Career"],
    collateralRequired: 10000,
    nextPayout: "2025-01-28",
    myTurn: true,
    nextTurnMember: "You",
    status: "active",
    unreadMessages: 0,
    currency: "KES",
    isPublic: false,
  },
  {
    id: 3,
    name: "University Alumni Fund",
    description:
      "Alumni network supporting each other's financial goals and education initiatives",
    members: 6,
    totalMembers: 15,
    maxMembers: 15,
    contribution: 3000,
    frequency: "Monthly",
    duration: "15 months",
    rating: 4.5,
    category: "Education",
    location: "Nairobi",
    tags: ["Alumni", "Education", "Network"],
    collateralRequired: 3000,
    nextPayout: "2025-03-10",
    myTurn: false,
    nextTurnMember: "John Kamau",
    status: "pending",
    unreadMessages: 1,
    currency: "KES",
    isPublic: false,
  },
];

export const mockPublicChamas = [
  {
    id: 4,
    name: "Digital Nomads Savings",
    description:
      "For remote workers and freelancers building financial security",
    members: 8,
    maxMembers: 12,
    contribution: 8000,
    frequency: "Monthly",
    duration: "12 months",
    rating: 4.8,
    category: "Professional",
    location: "Global",
    tags: ["Remote Work", "Tech", "Global"],
    collateralRequired: 8000,
    nextPayout: "2025-02-10",
    currency: "KES",
    isPublic: true,
  },
  {
    id: 5,
    name: "Small Business Owners Circle",
    description: "Supporting entrepreneurs and small business growth",
    members: 6,
    maxMembers: 10,
    contribution: 15000,
    frequency: "Monthly",
    duration: "10 months",
    rating: 4.9,
    category: "Business",
    location: "Nairobi",
    tags: ["Entrepreneurship", "SME", "Growth"],
    collateralRequired: 15000,
    nextPayout: "2025-01-30",
    currency: "KES",
    isPublic: true,
  },
];

export const mockMembers = [
  {
    id: "1",
    name: "Alice Wanjiku",
    role: "admin",
    joined: "2024-10-01",
    status: "active",
    contributions: 12000,
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face",
  },
  {
    id: "2",
    name: "John Kamau",
    role: "member",
    joined: "2024-10-01",
    status: "active",
    contributions: 12000,
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face",
  },
  {
    id: "3",
    name: "Grace Njeri",
    role: "member",
    joined: "2024-10-01",
    status: "active",
    contributions: 12000,
    avatar:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face",
  },
  {
    id: "4",
    name: "Sarah Njeri",
    role: "member",
    joined: "2024-10-01",
    status: "active",
    contributions: 12000,
    avatar:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face",
  },
];

export const mockTransactions = [
  {
    id: "1",
    type: "contribution",
    amount: 10000,
    chama: "Tech Developers Circle",
    date: "2025-01-24T14:30:00Z",
    status: "completed",
    hash: "0x742d35Cc6Cd3C9C4F6",
  },
  {
    id: "2",
    type: "payout",
    amount: 120000,
    chama: "Tech Developers Circle",
    date: "2025-01-20T10:00:00Z",
    status: "completed",
    hash: "0x8f3e2A9d7B5c1E4f8",
  },
];

export const mockPayoutSchedule = [
  {
    position: 1,
    member: {
      id: "1",
      name: "Alice Wanjiku",
      avatar:
        "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=50&h=50&fit=crop&crop=face",
      joinDate: "2024-10-01",
    },
    date: "2024-12-10",
    amount: 120000,
    status: "completed",
    contributions: 12000,
  },
  {
    position: 2,
    member: {
      id: "2",
      name: "John Kamau",
      avatar:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop&crop=face",
      joinDate: "2024-10-01",
    },
    date: "2025-01-10",
    amount: 120000,
    status: "completed",
    contributions: 12000,
  },
  {
    position: 3,
    member: {
      id: "3",
      name: "Grace Njeri",
      avatar:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50&h=50&fit=crop&crop=face",
      joinDate: "2024-10-01",
    },
    date: "2025-02-10",
    amount: 120000,
    status: "current",
    contributions: 12000,
  },
];
