-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycDocumentType" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycFirstName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycLastName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycFullName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycDateOfBirth" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycDocumentNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "kycNationality" TEXT;
